import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import Navbar from './navbar'
import Sidebar from './sidebar'
import { style } from '@mui/system'
import ListMovies from './movie'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Aria's Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.home}>
        <Sidebar />
        <div className={styles.homeContainer}>
          <Navbar />
          <div className={styles.widget}>
            <div className={styles.judul}>
              <h2>TRENDING</h2>
            </div>
            <ListMovies/>
          </div>
          <div className={styles.widget}>
            <div className={styles.judul}>
              <h2>CONTINUE</h2>
            </div>
            <ListMovies/>
          </div>
        </div>
      </div>
        
    </>
  )
}
